Repository mkaring/ConfuserEx, pull requests merged in 2021-07, with the labels that each got.

#366 Implement ParamDef copy
  Confuser.Core/Helpers/InjectHelper.cs
Labels: enhancement

#372 Add more error info when method not found
  Confuser.Renamer/VTable.cs
Labels: enhancement

#304 Changing header of compression block to 4 byte integer
  Confuser.Core/Services/CompressionService.cs
  Confuser.Runtime/Lzma.cs
Labels: bug

#378 Add test MessageDeobfuscationWithSymbolsMap for sequential rename mode
  Tests/MessageDeobfuscation.Test/MessageDeobfuscationTest.cs
Labels: enhancement

#374 Using cache during analysis phase
  Confuser.Core/Marker.cs
  Confuser.Renamer/AnalyzePhase.cs
Labels: enhancement

#384 Renaming improvements
  Confuser.Renamer/AnalyzePhase.cs
  Confuser.Renamer/Analyzers/VTableAnalyzer.cs
  Confuser.Renamer/DisplayNormalizedName.cs
  Confuser.Renamer/MessageDeobfuscator.cs
  Confuser.Renamer/NameService.cs
  Confuser.Renamer/ReferenceUtilities.cs
  Confuser.Renamer/ReversibleRenamer.cs
  ConfuserEx/StackTraceDecoder.xaml.cs
  Tests/MessageDeobfuscation.Test/MessageDeobfuscationTest.cs
  Tests/MessageDeobfuscation/Program.cs
  Tests/MethodOverloading.Test/MethodOverloadingTest.cs
  Tests/MethodOverloading/Program.cs
Labels: enhancement

#391 Case insensitive handling of culture identifier
  Confuser.Renamer/Analyzers/ResourceAnalyzer.cs
  Tests/389_MixedCultureCasing.Test/389_MixedCultureCasing.Test.csproj
  Tests/389_MixedCultureCasing.Test/MixedCultureCasingTest.cs
  Tests/389_MixedCultureCasing/389_MixedCultureCasing.csproj
  Tests/389_MixedCultureCasing/Program.cs
  Tests/389_MixedCultureCasing/Resource1.Designer.cs
  Tests/389_MixedCultureCasing/Resource1.de-DE.resx
  Tests/389_MixedCultureCasing/Resource1.resx
  Tests/389_MixedCultureCasing/Resource2.Designer.cs
  Tests/389_MixedCultureCasing/Resource2.de-de.resx
  Tests/389_MixedCultureCasing/Resource2.resx
Labels: bug

#392 Fixed readme file
  README.md
Labels: documentation
