Repository mkaring/ConfuserEx, pull requests merged in 2021-01, with the labels that each got.

#277 Improving assembly resolver
  Confuser.Core/ConfuserAssemblyResolver.cs
Labels: bug

#284 Copy symbols.map file during msbuild build
  Confuser.MSBuild.Tasks/build/Confuser.MSBuild.targets
Labels: bug

#286 Namespace format
  Confuser.Renamer/NameService.cs
  Confuser.Renamer/Properties/Resources.Designer.cs
  Confuser.Renamer/Properties/Resources.resx
  Confuser.Renamer/RenamePhase.cs
Labels: documentation, enhancement

#273 #270 Disable array constant obfuscation for non-primitive arrays
  Confuser.Protections/Constants/EncodePhase.cs
  Confuser2.sln
  Tests/270_EnumArrayConstantProtection.Test/270_EnumArrayConstantProtection.Test.csproj
  Tests/270_EnumArrayConstantProtection.Test/ConstantProtectionTest.cs
  Tests/270_EnumArrayConstantProtection/270_EnumArrayConstantProtection.csproj
  Tests/270_EnumArrayConstantProtection/Level.cs
  Tests/270_EnumArrayConstantProtection/Program.cs
Labels: bug

#282 Fix jump mangler
  Confuser.Protections/ControlFlow/JumpMangler.cs
Labels: bug

#289 Solved reference proxy error
  Confuser.Core/Helpers/MutationHelper.cs
  Confuser2.sln
  Tests/ReferenceProxy.Test/ReferenceProxy.Test.csproj
  Tests/ReferenceProxy.Test/ReferenceProxyTest.cs
  Tests/ReferenceProxy/Program.cs
  Tests/ReferenceProxy/ReferenceProxy.csproj
Labels: bug

#300 do not swallow decision basis
  Confuser.Core/ObfAttrMarker.cs
Labels: enhancement

#309 Fix handling of fully foreign vtable slots
  Confuser.Renamer/Analyzers/VTableAnalyzer.cs
  Confuser2.sln
  Tests/306_ComplexClassStructureRename.Lib/306_ComplexClassStructureRename.Lib.csproj
  Tests/306_ComplexClassStructureRename.Lib/ITestEvents.cs
  Tests/306_ComplexClassStructureRename.Lib/InternalBaseClass.cs
  Tests/306_ComplexClassStructureRename.Lib/InternalClass1.cs
  Tests/306_ComplexClassStructureRename.Lib/InternalClass2.cs
  Tests/306_ComplexClassStructureRename.Lib/MyTest.cs
  Tests/306_ComplexClassStructureRename.Lib/PublicClass1.cs
  Tests/306_ComplexClassStructureRename.Lib/PublicClass2.cs
  Tests/306_ComplexClassStructureRename.Test/306_ComplexClassStructureRename.Test.csproj
  Tests/306_ComplexClassStructureRename.Test/ComplexRenameTest.cs
  Tests/306_ComplexClassStructureRename/306_ComplexClassStructureRename.csproj
  Tests/306_ComplexClassStructureRename/Program.cs
  Tests/Confuser.UnitTest/TestBase.cs
Labels: bug
